# Generated by Django 2.0.1 on 2020-03-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200305_0658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='location',
            new_name='p_location',
        ),
    ]
