# Generated by Django 2.0.1 on 2020-03-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200305_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_country',
            name='country',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='p_country',
            name='sort_name',
            field=models.CharField(max_length=250),
        ),
    ]
